spring:
  application:
    name: mall
  profiles:
    active: dev #默认为开发环境
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M
      location: D:\file\mall\uploads
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  devtools:
    livereload:
      port: 35730
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: republic-slave #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  ignored:
    urls:
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /druid/**
      - /business/login
      - /business/info
      - /business/logout
      - /business/getCaptcha
      - /upload/**
redis:
  database: customer
  key:
    captcha: 'captcha'
  expire:
    common: 86400 # 24小时

amap:
  key: 6af7985ab67e64b8c6d0c87eec1aa40a