server:
  port: 8080
  file_url: http://localhost:8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/meituan?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 12345
    druid:
      initizl-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数\
      max-active: 20 #最大连接数
      web-stat-filter:
        enabled: true
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        enabled: true
        login-username: druid
        login-password: druid
      filter:
        stat:
          enabled: true
        wall:
          enabled: true

  redis:
    host: 127.0.0.1 #Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 500ms # 连接超时时间（毫秒）
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

logging:
  level:
    root: info
    com.heng.mall: debug
