server:
  port: 8080
  file_url: http://localhost:8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/waimai?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  redis:
    host: 127.0.0.1 #Redis服务器地址
    database: 1 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 500ms # 连接超时时间（毫秒）
logging:
  level:
    root: info
    com.heng.mall: debug
